---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:9.1.1
  when: {event: [push]}
  depends_on: []
  environment:
    GH_TOKEN:
      from_secret: gh_token

- name: test
  image: node:14-alpine
  commands: ["npm run test:ci -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: gh_token
    NPM_TOKEN:
      from_secret: npm_token

trigger:
  event: [push]
---
kind: signature
hmac: 444a201fd452be57c705e99cdc788d5bf2fcba7d5d08955ea4453e9617d02407

...
